name: Publish
on:
  push:
    branches:
      - main

jobs:
  verify-posix:
    uses: ./.github/workflows/verify-posix.yaml

  verify-windows:
    uses: ./.github/workflows/verify-windows.yaml

  generate-matrix:
    needs: [verify-posix, verify-windows]
    name: Generate Job Matrix
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.set-matrix.outputs.exists }}
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno run -A tasks/publish-matrix.ts
        id: set-matrix

  jsr:
    if: github.ref == 'refs/heads/main' && fromJSON(needs.generate-matrix.outputs.exists)
    name: Publish ${{ matrix.name }}@${{matrix.version}} to JSR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    needs: [generate-matrix]

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix: ${{fromJSON(needs.generate-matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4.2.0
      - uses: denoland/setup-deno@v2

      - run: deno publish --token=${{ secrets.JSR_TOKEN }}
        working-directory: ${{ matrix.workspace }}

  npm:
    if: github.ref == 'refs/heads/main' && fromJSON(needs.generate-matrix.outputs.exists)
    name: Publish ${{ matrix.name }}@${{matrix.version}} to NPM
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    needs: [generate-matrix]

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix: ${{fromJSON(needs.generate-matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4.2.0
      - uses: denoland/setup-deno@v2
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - run: deno run -A tasks/build-npm.ts ${{matrix.workspace}}

      - run: npm publish --access=public --tag=latest
        working-directory: ${{matrix.workspace}}/build/npm

  tag:
    if: github.ref == 'refs/heads/main' && fromJSON(needs.generate-matrix.outputs.exists)
    name: "Tag Release"
    runs-on: ubuntu-latest
    needs: [generate-matrix, jsr, npm]

    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.generate-matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4.2.0
        with:
          token: ${{secrets.FRONTSIDEJACK_GITHUB_TOKEN}}
      - run: git tag ${{ matrix.tagname }}
      - run: git push origin --tags
